name: testing new branch
on: 
 push:
 pull_request:
  branches:
  - 'pull-requet-new'
  
jobs:
 testing:
   runs-on: ubuntu-latest
   steps:
    - name: Test 1
      run: echo "This is first updated workflow"
    